const DATA=[
[2017,42,false,0,250000],[2018,68,false,0,250000],[2019,91,true,18000,250000],
[2020,90,true,12000,250000],[2021,53,false,0,250000],[2022,110,true,35000,250000],
[2023,82,true,15000,250000],[2024,125,true,47000,250000],[2025,61,false,0,250000]];
const PACK={basic:["الباقة الأساسية",5000,300],advanced:["الباقة المتقدمة",10000,550],full:["الباقة الشاملة",20000,950]};
let s=JSON.parse(localStorage.getItem("riskora")||"null")||{login:false,page:"home",pkg:"basic",dark:false,policy:null,notes:[]};
const save=()=>localStorage.setItem("riskora",JSON.stringify(s));
function analysis(){let losses=DATA.filter(x=>x[2]),p=losses.length/DATA.length,avg=losses.reduce((a,x)=>a+x[3],0)/losses.length,exp=p*avg;
let rows=[60,65,70,75,80,85,90,95,100].map(t=>{let h=DATA.filter(x=>x[1]>=t),hp=h.length/DATA.length,av=h.length?h.reduce((a,x)=>a+x[3],0)/h.length:0,el=hp*av,score=Math.max(0,100-Math.abs(el-exp)/Math.max(exp,1)*100);return[t,h.length,hp,av,el,score]});
return{p,avg,exp,rows,best:rows.reduce((a,b)=>b[5]>a[5]?b:a)}}
function go(p){s.page=p;save();render()}
function layout(body){return `<header class="topbar"><button class="icon" onclick="go('menu')">☰</button><div class="brand"><span class="logo">R</span>مرصد رسكاورا</div><button class="icon" onclick="go('notes')">🔔</button></header><main class="main">${body}</main><footer class="bottom"><div class="bottom-inner"><button class="nav ${s.page==='home'?'active':''}" onclick="go('home')">الرئيسية</button><button class="nav ${s.page==='coverage'?'active':''}" onclick="go('coverage')">تغطياتي</button><button class="nav ${s.page==='claims'?'active':''}" onclick="go('claims')">التعويضات</button><button class="nav ${s.page==='support'?'active':''}" onclick="go('support')">الدعم</button><button class="nav ${s.page==='account'?'active':''}" onclick="go('account')">حسابي</button></div></footer>`}
function render(){document.body.classList.toggle("dark",s.dark);if(!s.login){app.innerHTML=`<div class="login"><div class="loginbox"><div class="brand"><span class="logo">R</span>Mirsad Riskora</div><h1>مرحبًا بك</h1><p class="muted">نموذج تجريبي لمنصة التأمين البارامتري.</p><div class="form"><div class="field"><label>اسم المستخدم</label><input value="demo"></div><div class="field"><label>كلمة المرور</label><input type="password" value="123456"></div><button class="btn primary" onclick="s.login=true;save();render()">دخول تجريبي</button></div><p class="muted">demo / 123456</p></div></div>`;return}
let a=analysis(),body="";
if(s.page==="home")body=`<section class="hero"><h1>مرصد رسكاورا</h1><p>منصة رقمية لتحليل مخاطر الكوارث الطبيعية باستخدام البيانات والاحتمالات والرياضيات التأمينية.</p><div class="actions"><button class="btn primary" onclick="go('hazard')">ابدأ الآن</button><button class="btn secondary" onclick="go('analysis')">عرض التحليل</button></div></section><div class="grid"><div class="card"><h2>النموذج الحالي</h2><p class="muted">تحليل تجريبي لمخاطر الأمطار للفترة 2017–2025.</p><div class="metric-grid"><div class="metric">السنوات<strong>9</strong></div><div class="metric">حالات الضرر<strong>5</strong></div><div class="metric">احتمال الضرر<strong>${(a.p*100).toFixed(1)}%</strong></div><div class="metric">أفضل حد<strong>${a.best[0]} mm</strong></div></div></div><div class="card"><h2>تنبيه البيانات</h2><div class="notice">البيانات الحالية تجريبية ومخصصة لاختبار النموذج الرياضي، وليست بيانات أرصاد رسمية.</div></div></div>`;
else if(s.page==="hazard")body=`<div class="card"><h2>إعداد التغطية</h2><div class="form"><div class="field"><label>نوع الخطر</label><select><option>أمطار غزيرة / سيول</option><option>رياح شديدة</option><option>حرارة شديدة</option><option>عواصف رملية</option></select></div><div class="field"><label>المدينة</label><select><option>تبوك</option><option>الرياض</option><option>المدينة المنورة</option><option>جدة</option></select></div><div class="field"><label>باقة التغطية</label><div class="grid">${Object.entries(PACK).map(([k,v])=>`<div class="package ${s.pkg===k?'active':''}" onclick="s.pkg='${k}';save();render()"><h3>${v[0]}</h3><p>تغطية ${v[1].toLocaleString()} ر.س</p><strong>${v[2]} ر.س</strong></div>`).join("")}</div></div><button class="btn primary" onclick="go('analysis')">ابدأ التحليل</button></div></div>`;
else if(s.page==="analysis")body=`<div class="card"><h2>تحليل المخاطر</h2><div class="metric-grid"><div class="metric">احتمال الضرر<strong>${(a.p*100).toFixed(1)}%</strong></div><div class="metric">متوسط الضرر<strong>${Math.round(a.avg).toLocaleString()} ر.س</strong></div><div class="metric">الخسارة المتوقعة<strong>${Math.round(a.exp).toLocaleString()} ر.س</strong></div><div class="metric">نقطة التعويض<strong>${a.best[0]} mm</strong></div></div><h3>مقارنة نقاط التعويض</h3><div class="table-wrap"><table class="table"><tr><th>الحد</th><th>التجاوز</th><th>الاحتمال</th><th>الخسارة المتوقعة</th><th>التقييم</th></tr>${a.rows.map(r=>`<tr><td>${r[0]} mm</td><td>${r[1]}</td><td>${(r[2]*100).toFixed(1)}%</td><td>${Math.round(r[4]).toLocaleString()}</td><td>${r[5].toFixed(1)}</td></tr>`).join("")}</table></div><div class="actions"><button class="btn primary" onclick="go('quote')">عرض الباقة المقترحة</button></div></div>`;
else if(s.page==="quote"){let p=PACK[s.pkg];body=`<div class="card"><h2>الباقة المقترحة</h2><div class="metric-grid"><div class="metric">الباقة<strong>${p[0]}</strong></div><div class="metric">التغطية<strong>${p[1].toLocaleString()} ر.س</strong></div><div class="metric">القسط<strong>${p[2]} ر.س</strong></div><div class="metric">المحفز<strong>${a.best[0]} mm</strong></div></div><p class="muted">شرط التعويض: تحقق مؤشر الأمطار المحدد مسبقًا وفق شروط الوثيقة.</p><button class="btn primary" onclick="go('payment')">متابعة للدفع التجريبي</button></div>`}
else if(s.page==="payment"){let p=PACK[s.pkg];body=`<div class="card"><h2>الدفع التجريبي</h2><p class="muted">لا يتم خصم أي مبلغ حقيقي.</p><div class="form"><div class="field"><label>رقم بطاقة تجريبية</label><input value="4111 1111 1111 1111"></div><button class="btn primary" onclick="s.policy={pkg:s.pkg,trigger:a.best[0],coverage:p[1],premium:p[2]};s.notes.unshift('تم تفعيل وثيقة رسكاورا التجريبية');save();go('activation')">دفع وتفعيل الوثيقة</button></div></div>`}
else if(s.page==="activation")body=`<div class="card"><h2>تم تفعيل الوثيقة</h2><p class="muted">تم إنشاء الوثيقة التجريبية بنجاح.</p><div class="metric-grid"><div class="metric">التغطية<strong>${s.policy.coverage.toLocaleString()} ر.س</strong></div><div class="metric">المحفز<strong>${s.policy.trigger} mm</strong></div><div class="metric">القسط<strong>${s.policy.premium} ر.س</strong></div><div class="metric">الحالة<strong>نشطة</strong></div></div><button class="btn primary" onclick="go('coverage')">عرض وثيقتي</button></div>`;
else if(s.page==="coverage")body=`<div class="card"><h2>تغطياتي</h2>${s.policy?`<div class="package active"><h3>${PACK[s.policy.pkg][0]}</h3><p>الحالة: نشطة</p><p>التغطية: ${s.policy.coverage.toLocaleString()} ر.س</p><p>نقطة التعويض: ${s.policy.trigger} mm</p></div>`:`<p class="muted">لا توجد وثيقة نشطة.</p><button class="btn primary" onclick="go('hazard')">ابدأ الآن</button>`}</div>`;
else if(s.page==="claims")body=`<div class="card"><h2>التعويضات</h2><p class="muted">صفحة تجريبية لمتابعة التعويضات البارامترية.</p><div class="notice">${s.policy?"لا توجد مطالبة مستحقة حاليًا.":"فعّلي وثيقة أولًا."}</div></div>`;
else if(s.page==="notes")body=`<div class="card"><h2>الإشعارات</h2>${s.notes.length?s.notes.map(x=>`<div class="package">${x}</div>`).join(""):"<p class='muted'>لا توجد إشعارات.</p>"}</div>`;
else if(s.page==="support")body=`<div class="card"><h2>مساعد رسكاورا</h2><div id="chat" class="chat"><div class="msg bot">مرحبًا، اسأليني عن التأمين البارامتري أو طريقة عمل المنصة.</div></div><div class="row" style="margin-top:8px"><input id="q" placeholder="اكتبي سؤالك"><button class="btn primary" onclick="chat()">إرسال</button></div></div>`;
else if(s.page==="account")body=`<div class="grid"><div class="card"><h2>حسابي</h2><p class="muted">الحساب التجريبي: demo</p><button class="btn danger" onclick="s.login=false;save();render()">تسجيل الخروج</button></div><div class="card"><h2>الإعدادات</h2><button class="btn secondary" onclick="s.dark=!s.dark;save();render()">الوضع الداكن</button></div></div>`;
else body=`<div class="card"><h2>القائمة</h2><div class="actions"><button class="btn secondary" onclick="go('notes')">الإشعارات</button><button class="btn secondary" onclick="go('support')">الدعم</button><button class="btn secondary" onclick="go('account')">الحساب والإعدادات</button><button class="btn danger" onclick="s.login=false;save();render()">تسجيل الخروج</button></div></div>`;
app.innerHTML=layout(body)}
function chat(){let q=document.getElementById("q"),c=document.getElementById("chat");if(!q.value)return;c.innerHTML+=`<div class="msg user">${q.value}</div><div class="msg bot">مرصد رسكاورا نموذج أولي للتأمين البارامتري. يعتمد النموذج الحالي على بيانات تجريبية لاختبار تحليل المخاطر ونقاط التعويض.</div>`;q.value=""}
render();